title: FMT ONE
logo: /assets/img/logo.svg

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: "unnamed"
      author: "Marc Volker Dickmann"
gems:
  - jekyll-feed
  - jekyll-sitemap
